sudo: true
language: python

python:
  # - "2.6" throws error on Travis' side
  # - "2.7"
  # - "3.3" throws error on Travis' side
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"


before_install:
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar -xzvf proj-4.9.3.tar.gz
  - cd proj-4.9.3 && ./configure --prefix=/usr && make && sudo make install
  - sudo apt-get install proj-data # libproj-dev proj-bin
  - sudo apt-get install libgeos-* libgeos-dev libffi-dev libxslt1-dev libgdal-dev
  - sudo apt-get install python3-shapely python3-gdal python3-pyproj
  # - pip install -U cairocffi GDAL pyproj shapely
  # - pip install cartopy
  - pip install codecov tox # -U

install:
  - pip install .

script:
  - pytest
  # - coverage run --source htmldate tests/unit_tests.py
  # - tox

#cache:
#  - pip
#  - apt
