sudo: true
language: python

python:
  # - "2.6" throws error on Travis' side
  # - "2.7"
  # - "3.3" throws error on Travis' side
  - "3.4"
  - "3.5"
  - "3.6"


before_install:
  - sudo apt-get install libproj-dev proj-data proj-bin
  - sudo apt-get install libgeos-* libgeos-dev libffi-dev libxslt1-dev libgdal-dev
  - pip install -U cairocffi exrex pyproj requests shapely
  - pip install cartopy
  # - pip install -U codecov tox

install:
  - pip install .

script:
  - pytest
  # - coverage run --source htmldate tests/unit_tests.py
  # - tox

cache:
  - pip
  - apt
