sudo: true
language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    # - python: "3.3"
    #   env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37
  allow_failures:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.7-dev"
      env: TOXENV=py37
  # fast_finish: true


before_install:
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar -xzvf proj-4.9.3.tar.gz
  - cd proj-4.9.3 && ./configure --prefix=/usr && make && sudo make install
  - cd ..
  - sudo apt-get install proj-data # libproj-dev proj-bin
  - sudo apt-get install libgeos-* libgeos-dev libffi-dev libxslt1-dev libgdal-dev
  - sudo apt-get install python3-shapely python3-gdal python3-pyproj
  # - pip install -U cairocffi GDAL pyproj shapely
  # - pip install cartopy
  - pip install -U codecov tox

install:
  - pwd
  - ls -al
  - pip install .

script:
  - tox

after_success:
  - codecov

#cache:
#  - pip
#  - apt
